name: C++ CI - Autotest
on:
  push:
    branches: [ branchAutoTest ]
  pull_request:
    branches: [ branchAutoTest ]
  workflow_dispatch:
    branches: [ branchAutoTest ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool build-essential
    - name: Generate configure script
      run: autoreconf -i
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Run check
      run: make check
