name: C++ CI

on:
  push:
    branches: [ branchMake, main ]
  pull_request:
    branches: [ branchMake, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ./configure
      run: ./configure
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++
    
    - name: Build with Make
      run: make

    - name: create distribution tarball
      run: make dist
